name: Develop Environment

on: develop environment

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "bye world"

