name: Develop Environment

on:
  push:
    branches:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install dependencies
        run: npm run
      - name: Run test
        run: |
          echo "npm test"

