name: Linting S3 BUCKET
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing_buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AIM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com
      - name: List S3 buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Listing S3 buckets"
          aws s3 ls